/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StartupsRouteImport } from './routes/startups'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartupsIndexRouteImport } from './routes/startups.index'
import { Route as InvestorsIndexRouteImport } from './routes/investors.index'
import { Route as StartupsSlugRouteImport } from './routes/startups.$slug'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsRoute = StartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsIndexRoute = StartupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StartupsRoute,
} as any)
const InvestorsIndexRoute = InvestorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvestorsRoute,
} as any)
const StartupsSlugRoute = StartupsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StartupsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/investors': typeof InvestorsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/startups': typeof StartupsRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/startups/$slug': typeof StartupsSlugRoute
  '/investors/': typeof InvestorsIndexRoute
  '/startups/': typeof StartupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/startups/$slug': typeof StartupsSlugRoute
  '/investors': typeof InvestorsIndexRoute
  '/startups': typeof StartupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/investors': typeof InvestorsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/startups': typeof StartupsRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/startups/$slug': typeof StartupsSlugRoute
  '/investors/': typeof InvestorsIndexRoute
  '/startups/': typeof StartupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/investors'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/startups'
    | '/verify-email'
    | '/startups/$slug'
    | '/investors/'
    | '/startups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/startups/$slug'
    | '/investors'
    | '/startups'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/investors'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/startups'
    | '/verify-email'
    | '/startups/$slug'
    | '/investors/'
    | '/startups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvestorsRoute: typeof InvestorsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  StartupsRoute: typeof StartupsRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups': {
      id: '/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof StartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/': {
      id: '/startups/'
      path: '/'
      fullPath: '/startups/'
      preLoaderRoute: typeof StartupsIndexRouteImport
      parentRoute: typeof StartupsRoute
    }
    '/investors/': {
      id: '/investors/'
      path: '/'
      fullPath: '/investors/'
      preLoaderRoute: typeof InvestorsIndexRouteImport
      parentRoute: typeof InvestorsRoute
    }
    '/startups/$slug': {
      id: '/startups/$slug'
      path: '/$slug'
      fullPath: '/startups/$slug'
      preLoaderRoute: typeof StartupsSlugRouteImport
      parentRoute: typeof StartupsRoute
    }
  }
}

interface InvestorsRouteChildren {
  InvestorsIndexRoute: typeof InvestorsIndexRoute
}

const InvestorsRouteChildren: InvestorsRouteChildren = {
  InvestorsIndexRoute: InvestorsIndexRoute,
}

const InvestorsRouteWithChildren = InvestorsRoute._addFileChildren(
  InvestorsRouteChildren,
)

interface StartupsRouteChildren {
  StartupsSlugRoute: typeof StartupsSlugRoute
  StartupsIndexRoute: typeof StartupsIndexRoute
}

const StartupsRouteChildren: StartupsRouteChildren = {
  StartupsSlugRoute: StartupsSlugRoute,
  StartupsIndexRoute: StartupsIndexRoute,
}

const StartupsRouteWithChildren = StartupsRoute._addFileChildren(
  StartupsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvestorsRoute: InvestorsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  StartupsRoute: StartupsRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
